import Header from "@/components/header";
import Search from "@/components/search";
import Head from "next/head";
import React from "react";
import { useState } from "react";
import Dashboard from "./dashboard";
import * as S from "../styled/homeStyled.js";

const Home = () => {
  const [projects, setProjects] = useState([]);
  const [active, setActive] = useState(0);
  const [searchSlide, setSearchSlide] = useState(false);
  const [showMobileSideBar, setShowMobileSideBar] = useState(false);

  const handleAdd = (index) => {
    setActive(index);
  };

  return (
    <S.Home searchSlide={searchSlide}>
      <Head>
        <title>IKOORU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="root-dashboard">
        <Dashboard
          showMobileSideBar={showMobileSideBar}
          setShowMobileSideBar={setShowMobileSideBar}
          setSearchSlide={setSearchSlide}
          searchSlide={searchSlide}
          projects={projects || []}
          active={active}
          setActive={setActive}
          handleAdd={handleAdd}
          setProjects={setProjects}
        />
      </div>
    </S.Home>
  );
};
export default Home;
